/*
    Modern Web Programming
    Homework 1 Recipe
    fronteffects.js
    js for index.html
    made by the WordPress's theme Optimizer
    Copyright By Haswell © 2016 All Rights Reserved.
    School of Data and Computer Science
    Sun Yat-sen University
    2016-09-11
*/
!function (a) { a.fn.hoverIntent = function (b, c, d) { var e = { interval: 100, sensitivity: 6, timeout: 0 }; e = "object" == typeof b ? a.extend(e, b) : a.isFunction(c) ? a.extend(e, { over: b, out: c, selector: d }) : a.extend(e, { over: b, out: b, selector: c }); var f, g, h, i, j = function (a) { f = a.pageX, g = a.pageY }, k = function (b, c) { return c.hoverIntent_t = clearTimeout(c.hoverIntent_t), Math.sqrt((h - f) * (h - f) + (i - g) * (i - g)) < e.sensitivity ? (a(c).off("mousemove.hoverIntent", j), c.hoverIntent_s = !0, e.over.apply(c, [b])) : (h = f, i = g, c.hoverIntent_t = setTimeout(function () { k(b, c) }, e.interval), void 0) }, l = function (a, b) { return b.hoverIntent_t = clearTimeout(b.hoverIntent_t), b.hoverIntent_s = !1, e.out.apply(b, [a]) }, m = function (b) { var c = a.extend({}, b), d = this; d.hoverIntent_t && (d.hoverIntent_t = clearTimeout(d.hoverIntent_t)), "mouseenter" === b.type ? (h = c.pageX, i = c.pageY, a(d).on("mousemove.hoverIntent", j), d.hoverIntent_s || (d.hoverIntent_t = setTimeout(function () { k(c, d) }, e.interval))) : (a(d).off("mousemove.hoverIntent", j), d.hoverIntent_s && (d.hoverIntent_t = setTimeout(function () { l(c, d) }, e.timeout))) }; return this.on({ "mouseenter.hoverIntent": m, "mouseleave.hoverIntent": m }, e.selector) } }(jQuery);; !function (a, b) { "use strict"; function c() { if (!e) { e = !0; var a, c, d, f, g = -1 !== navigator.appVersion.indexOf("MSIE 10"), h = !!navigator.userAgent.match(/Trident.*rv:11\./), i = b.querySelectorAll("iframe.wp-embedded-content"); for (c = 0; c < i.length; c++) if (d = i[c], !d.getAttribute("data-secret")) { if (f = Math.random().toString(36).substr(2, 10), d.src += "#?secret=" + f, d.setAttribute("data-secret", f), g || h) a = d.cloneNode(!0), a.removeAttribute("security"), d.parentNode.replaceChild(a, d) } else; } } var d = !1, e = !1; if (b.querySelector) if (a.addEventListener) d = !0; if (a.wp = a.wp || {}, !a.wp.receiveEmbedMessage) if (a.wp.receiveEmbedMessage = function (c) { var d = c.data; if (d.secret || d.message || d.value) if (!/[^a-zA-Z0-9]/.test(d.secret)) { var e, f, g, h, i, j = b.querySelectorAll('iframe[data-secret="' + d.secret + '"]'), k = b.querySelectorAll('blockquote[data-secret="' + d.secret + '"]'); for (e = 0; e < k.length; e++) k[e].style.display = "none"; for (e = 0; e < j.length; e++) if (f = j[e], c.source === f.contentWindow) { if (f.removeAttribute("style"), "height" === d.message) { if (g = parseInt(d.value, 10), g > 1e3) g = 1e3; else if (~~g < 200) g = 200; f.height = g } if ("link" === d.message) if (h = b.createElement("a"), i = b.createElement("a"), h.href = f.getAttribute("src"), i.href = d.value, i.host === h.host) if (b.activeElement === f) a.top.location.href = d.value } else; } }, d) a.addEventListener("message", a.wp.receiveEmbedMessage, !1), b.addEventListener("DOMContentLoaded", c, !1), a.addEventListener("load", c, !1) }(window, document);